import { Song } from './Api';

export const MOCK_SONGS: Song[] = [
  {
    video_id: '1',
    title: 'Bohemian Rhapsody',
    channel: 'QueenOfficial',
    duration: 355,
    thumbnail_url: null,
    artist: 'Queen',
    album: 'A Night at the Opera',
  },
  {
    video_id: '2',
    title: 'Stairway to Heaven',
    channel: 'LedZeppelin',
    duration: 482,
    thumbnail_url: null,
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
  },
  {
    video_id: '3',
    title: 'Hotel California',
    channel: 'EaglesVEVO',
    duration: 390,
    thumbnail_url: null,
    artist: 'Eagles',
    album: 'Hotel California',
  },
  {
    video_id: '4',
    title: 'Imagine',
    channel: 'johnlennon',
    duration: 183,
    thumbnail_url: null,
    artist: 'John Lennon',
    album: 'Imagine',
  },
  {
    video_id: '5',
    title: "Sweet Child O' Mine",
    channel: 'GunsNRosesVEVO',
    duration: 356,
    thumbnail_url: null,
    artist: "Guns N' Roses",
    album: 'Appetite for Destruction',
  },
  {
    video_id: '6',
    title: 'Billie Jean',
    channel: 'michaeljacksonVEVO',
    duration: 294,
    thumbnail_url: null,
    artist: 'Michael Jackson',
    album: 'Thriller',
  },
  {
    video_id: '7',
    title: 'Smells Like Teen Spirit',
    channel: 'NirvanaVEVO',
    duration: 301,
    thumbnail_url: null,
    artist: 'Nirvana',
    album: 'Nevermind',
  },
  {
    video_id: '8',
    title: 'Purple Rain',
    channel: 'prince',
    duration: 521,
    thumbnail_url: null,
    artist: 'Prince',
    album: 'Purple Rain',
  },
  {
    video_id: '9',
    title: 'Like a Rolling Stone',
    channel: 'bobdylanVEVO',
    duration: 373,
    thumbnail_url: null,
    artist: 'Bob Dylan',
    album: 'Highway 61 Revisited',
  },
  {
    video_id: '10',
    title: 'Come Together',
    channel: 'TheBeatlesVEVO',
    duration: 260,
    thumbnail_url: null,
    artist: 'The Beatles',
    album: 'Abbey Road',
  },
];
